In [42]:
import numpy as np
print("*"*25)
a = np.array([1,2,3])
print(a)
print(type(a))
print("*"*25)
two_D = np.array([[1,2,3],[4,5,6]],)
print(two_D)
print(type(two_D))
print("*"*25)
three_D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(three_D)
print("*"*25)
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

print("*"*25)

# array to list
lst = (a.tolist())
lst_ = np.array(lst)
print(lst)
print(type(lst))
print(lst_)

print(a==lst)
print("*"*25)
print(sorted(a))







*************************
[1 2 3]
<class 'numpy.ndarray'>
*************************
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
*************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
*************************
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
*************************
[1, 2, 3]
<class 'list'>
[1 2 3]
[ True  True  True]
*************************
[1, 2, 3]


In [43]:
print("*"*25)
# adding elements to the array
a = np.array([1,24])
a = np.append(a,3)
print(a)
a = np.append(a,[6,7,8])
print(a)

print("*"*25)
# deleting the elements from the array
a = np.delete(a,0)          # zeroth index element will get deleteted
print(a)

print("*"*25)
# inserting the elements to the array
a = np.insert(a,0,100)              # zeroth elemet will replaced by 100
print(a)

# another way to update the elements
a[-2] = 200         # by using index we can update the elements
print(a)

print("*"*25)

*************************
[ 1 24  3]
[ 1 24  3  6  7  8]
*************************
[24  3  6  7  8]
*************************
[100  24   3   6   7   8]
[100  24   3   6 200   8]
*************************


In [44]:
# for loop in numpy array
three_D = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in three_D:
    print(i)

print("*"*25)
i = 0           # intialize the index is mandatory
while i<len(three_D):
    print(three_D[i])
    i+=1

[1 2 3]
[4 5 6]
[7 8 9]
*************************
[1 2 3]
[4 5 6]
[7 8 9]


In [52]:
### time complexity of the array vs list.
# del list
my_list = list(range(1000000))
array = np.arange(1000000)
# executing list first
import time 
start = time.time()
for i in range(1000):
    if 50000000 in my_list:
        pass
end = time.time()
print(f"Time taken by list: {end-start} seconds")
print("*"*25)
# executing array first
start = time.time()
for i in range(1000):
    if 50000000 in array:
        pass
end = time.time()
print(f"Time taken by array: {end-start} seconds")
# to much faster are array than list.





Time taken by list: 21.507202625274658 seconds
*************************
Time taken by array: 0.17965364456176758 seconds


In [46]:
## own datatype numpy arrray
print("*"*25)
data = np.array([1,2,3],dtype=float)
print(data)
print("*"*25)
data = np.array([1,2,0],dtype=bool)
print(data)
print("*"*25)

data = np.array([1,2,0],dtype=complex)
print(data)
print("*"*25)


*************************
[1. 2. 3.]
*************************
[ True  True False]
*************************
[1.+0.j 2.+0.j 0.+0.j]
*************************


In [45]:
# np.arange:- create list of numbers between two similar to range function
print("*"*25)
array = np.arange(1,20)
print(array)

print("*"*25)
array = np.arange(1,20,2)
print(array)

*************************
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
*************************
[ 1  3  5  7  9 11 13 15 17 19]


In [47]:
# reshape:- changes the dimension of the list which must be equal to product of max range
print("*"*25)
array = np.arange(1,21).reshape(4,5)
print(array)

print("*"*25)
array = np.arange(1,26).reshape(5,5)
print(array)

*************************
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
*************************
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
# ways to intialize arrays
print("*"*25)
# np.ones
ones = np.ones((3,4))
print(ones)
print("*"*25)
#np.zeros
zeroes = np.zeros((3,4))
print(zeroes)
print("*"*25)
# np.random.random
random = np.random.random((3,4))        # it will create 3X4 matrix
print(random)

*************************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
*************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*************************
[[0.29294526 0.54197414 0.51568172 0.90420834]
 [0.73721043 0.77750125 0.57033539 0.60777782]
 [0.02557279 0.72979201 0.12091221 0.39450973]]


In [50]:
# np.linespace:- create array of number between given two number and third gap implies the gap
np.linspace(-10,10,5)       # create array between two number(-10,10) with gap of 5 


array([-10.,  -5.,   0.,   5.,  10.])

In [10]:
# np.identity
print("*"*25)
print(np.identity(3))
print("*"*25)
print(np.identity(4))

*************************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*************************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### numpy attributes

In [11]:
a1 = np.arange(10)
a2 = np.arange(1,21).reshape(4,5)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
#n.dim:- written the dimesnion of the arrray either 1D, 2D or etc
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [58]:
# shape returns the rows and columns
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(4, 5)
(2, 2, 2)


In [13]:
# size:- returns the number of the elements
print(a1.size)
print(a2.size)
print(a3.size)

10
20
8


In [14]:
# item size
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [31]:
# dtype:- written the amount of memory it is taking
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


### changing datatypes

In [38]:
# power of astype
print(a3.astype(np.int8))
print(a3.astype("str"))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[['0' '1']
  ['2' '3']]

 [['4' '5']
  ['6' '7']]]


### Array operations

In [17]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [53]:
# scalar operations
print(a1*2)
print(a1+2)
print(a1-2)
print(a1**2)
print(a1//2)
print(a1%2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


### Converting Data Structure to Numpy array


In [54]:
import numpy as np

In [27]:
# converting list to numpy array
lst = [1,2,3,4,5]
array = np.array(lst)
print(array)
print(type(array))
print("*"*25)

lst_ = array.tolist()
print(lst_)
print(type(lst_))
print("*"*25)
# converting tuple to numpy array
tple = (1,2,3,4,5)
array = np.array(tple)
print(array)
print(type(array))
print("*"*25)



# converting set to numpy array
st = {1,2,3,4,5}
array = np.array(list(st))
print(array)
print(type(array))
print("*"*25)
print(str(array))
# converting string to numpy array
string = "Hello, World!"
array = np.array(list(string))
print(array)
print(type(array))
print("*"*25)

# converting dictionary to numpy array
dictionary = {"a":1, "b":2, "c":3}
array = np.array(dictionary)
print(array)
print(type(array))
print("*"*25)

print(np.array(dictionary.items()))


[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1, 2, 3, 4, 5]
<class 'list'>
*************************
[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1 2 3 4 5]
['H' 'e' 'l' 'l' 'o' ',' ' ' 'W' 'o' 'r' 'l' 'd' '!']
<class 'numpy.ndarray'>
*************************
{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
*************************
dict_items([('a', 1), ('b', 2), ('c', 3)])


### Converting the Datatype to Numpy array

In [26]:
arr = np.array([1,2,3,3,4])
print(arr)
print(arr.dtype)
print(arr.astype("float"))
arr_ = arr.astype(np.float16)
print(arr_.dtype)
print(arr_.astype("str"))
print(arr_.astype("bool"))


[1 2 3 3 4]
int32
[1. 2. 3. 3. 4.]
float16
['1.0' '2.0' '3.0' '3.0' '4.0']
[ True  True  True  True  True]


In [58]:
arr1 = np.array([1,2,3,4,5])
a = (str(arr1))
print(type(a))


# print(tuple(arr1))
print(list(arr1))
# del set
print(set(arr1))


<class 'str'>
[1, 2, 3, 4, 5]
{1, 2, 3, 4, 5}
