## Data Cleaning and analysis with NUMPY

### Dealing with Null Values

In [18]:
import numpy as np
# converting null into 
arr = np.array([1, 2, 3, None,4,5,6,None])
print(arr)
print(arr.dtype)

result = np.array([x is None for x in arr])
print(result)



print(arr[result])
print(arr[~result])

[1 2 3 None 4 5 6 None]
object
[False False False  True False False False  True]
[None None]
[1 2 3 4 5 6]


In [ ]:
# replacing null with 0
import numpy as np
arr = np.array([1, 2, 3, np.nan,4,5,6,np.nan])
print(arr)
arr[np.isnan(arr)] = 0
print(arr)

[ 1.  2.  3. nan  4.  5.  6. nan]
[1. 2. 3. 0. 4. 5. 6. 0.]


In [24]:
arr = np.array([1, 2, 3, np.nan,4,5,6,np.nan])

arr[np.isnan(arr)] = np.nanmean(arr)      # np.nan is used to represent missing values in numpy arrays
print(arr)

[1.  2.  3.  3.5 4.  5.  6.  3.5]
