#### `Numpy` = Numerical Python
 - provides fast, flexible tools to do mathematical operations, statistics, and data manipulation on large sets of numbers


 ##### Main Feature:-
- Powerful N-dimensional array object (ndarray)
- Tools for mathematical operations (sum, mean, std, etc.)
- Supports linear algebra, Fourier transform, and random number generation
- Super fast compared to vanilla Python

In [3]:
import numpy as np
print("*"*25)
a = np.array([1,2,3])
print(a)
print(type(a))
print("*"*25)
two_D = np.array([[1,2,3],[4,5,6]],)
print(two_D)
print(type(two_D))
print("*"*25)
three_D = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[1,2,3],[4,5,6],[7,8,9]],
                    [[1,2,3],[4,5,6],[7,8,9]]])
print(three_D)
print(three_D.ndim)
print("*"*25)
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

print("*"*25)

# array to list
lst = (a.tolist())
print(lst)
print(type(lst))
print(lst_)

print(a==lst)
print("*"*25)
print(sorted(a))







*************************
[1 2 3]
<class 'numpy.ndarray'>
*************************
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
*************************
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
*************************
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
*************************
[1, 2, 3]
<class 'list'>
[1 2 3]
[ True  True  True]
*************************
[1, 2, 3]


In [4]:
print("*"*25)
# adding elements to the array
a = np.array([1,24])
a = np.append(a,3)
print(a)
a = np.append(a,[6,7,8])
print(a)

print("*"*25)
# deleting the elements from the array
a = np.delete(a,0)          # zeroth index element will get deleteted
print(a)

print("*"*25)
# inserting the elements to the array
a = np.insert(a,0,100)              # zeroth elemet will replaced by 100
print(a)

# another way to update the elements
a[-2] = 200         # by using index we can update the elements
print(a)

print("*"*25)

*************************
[ 1 24  3]
[ 1 24  3  6  7  8]
*************************
[24  3  6  7  8]
*************************
[100  24   3   6   7   8]
[100  24   3   6 200   8]
*************************


In [5]:
# for loop in numpy array
three_D = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in three_D:
    print(i)

print("*"*25)
i = 0           # intialize the index is mandatory
while i<len(three_D):
    print(three_D[i])
    i+=1

[1 2 3]
[4 5 6]
[7 8 9]
*************************
[1 2 3]
[4 5 6]
[7 8 9]


In [6]:
import numpy as np
### time complexity of the array vs list.
# del list
my_list = list(range(1000000))
array = np.arange(1000000)
# executing list first
import time 
start = time.time()
for i in range(1000):
    if 50000000 in my_list:
        pass
end = time.time()
print(f"Time taken by list: {end-start} seconds")
print("*"*25)
# executing array first
start = time.time()
for i in range(1000):
    if 50000000 in array:
        pass
end = time.time()
print(f"Time taken by array: {end-start} seconds")
# to much faster are array than list.





Time taken by list: 21.754305839538574 seconds
*************************
Time taken by array: 0.21347737312316895 seconds


In [12]:
## own datatype numpy arrray
print("*"*25)
data = np.array([1,2,3],dtype=float)
print(type(data))
print("*"*25)
data = np.array([1,2,0],dtype="b")
print(type(data))
print("*"*25)

data = np.array([1,2,0],dtype=complex)
print(type(data))
print("*"*25)


data = np.array([1,2,0],dtype="O")
print(type(data))
print("*"*25)

# i= intger
# f = flaot
# u = unsigned chara
# c - complex flaoting
# a = ASCiI 
# b = boolean
# "O" = object
# "S" = string

*************************
<class 'numpy.ndarray'>
*************************
<class 'numpy.ndarray'>
*************************
<class 'numpy.ndarray'>
*************************
<class 'numpy.ndarray'>
*************************


In [45]:
# np.arange:- create list of numbers between two similar to range function
print("*"*25)
array = np.arange(1,20)
print(array)

print("*"*25)
array = np.arange(1,20,2)
print(array)

*************************
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
*************************
[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
# reshape:- changes the dimension of the list which must be equal to product of max range
print("*"*25)
array = np.arange(0,20).reshape(4,5)
print(array)

print("*"*25)
array = np.arange(1,26).reshape(5,5)
print(array)

*************************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
*************************
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
import numpy as np
# ways to intialize arrays
print("*"*25)
# np.ones
ones = np.ones((3,4))
print(ones)
print("*"*25)
#np.zeros
zeroes = np.zeros((3,4))
print(zeroes)
print("*"*25)
# np.random.random
random = np.random.random((3,4))        # it will create 3X4 matrix
print(random)
print("*"*25)
em = np.empty((2,2)) 
print(em)         # it will create empty array of 2 elements

*************************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
*************************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*************************
[[0.61959008 0.6157335  0.38519735 0.33486746]
 [0.23210617 0.27851606 0.70469662 0.41257754]
 [0.10088209 0.19957493 0.86576586 0.86840068]]
*************************
[[2.12199579e-314 1.15012172e-311]
 [4.90113121e-321 3.79442416e-321]]


In [4]:
import numpy as np

array = np.linspace(1,10,num = 10,retstep=True)       
print(array)

array_ = np.linspace(1,10,num = 5,retstep=True)         # retstep = True, it will return the step size as well in tuple form
print(array_)


arra = np.linspace(1,10,num = 10,retstep=False)      
print(arra)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [17]:
## logspace
print(np.logspace(1,10,5,base=2))       # it will create array between 10^1 to 10^10 with gap of 5
l = np.logspace(1,10,5,endpoint=False)     # it will create array between 10^1 to 10^10 with gap of 5   
print(l)

[   2.            9.51365692   45.254834    215.2694823  1024.        ]
[1.00000000e+01 6.30957344e+02 3.98107171e+04 2.51188643e+06
 1.58489319e+08]


In [17]:
# np.identity
print("*"*25)
print(np.identity(3,dtype = np.int32))
print("*"*25)
print(np.identity(4))

# eye
print(np.eye(3,dtype=(np.int8)))


*************************
[[1 0 0]
 [0 1 0]
 [0 0 1]]
*************************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### numpy attributes

In [18]:
a1 = np.arange(10)          # it will create single number list 
a2 = np.arange(1,21).reshape(4,5)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [19]:
#n.dim:- written the dimesnion of the arrray either 1D, 2D or etc
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [20]:
# shape returns the rows and columns
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(4, 5)
(2, 2, 2)


In [21]:
# size:- returns the number of the elements
print(a1.size)
print(a2.size)
print(a3.size)

10
20
8


In [22]:
# item size:- tells you how much memory (in bytes) each item of a NumPy array is taking.
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [23]:
# dtype:- written the amount of memory it is taking
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


### changing datatypes

In [24]:
# power of astype
print(a3.astype(np.int8))           # convert the array into int8
print(a3.astype("str"))             # convert the array into string
print(a3.astype("float"))
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.astype("str"))


arr = np.array([1, 2, 3, 4], dtype=str)
print(arr)        # ['1' '2' '3' '4']
print(arr.dtype)  # <U1 (Unicode string of length 1)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[['0' '1']
  ['2' '3']]

 [['4' '5']
  ['6' '7']]]
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
[1 2 3 4]
['1' '2' '3' '4']
['1' '2' '3' '4']
<U1


### Array operations

In [25]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [26]:
# scalar operations
print(a1*2)
print(a1+2)
print(a1-2)
print(a1**2)
print(a1//2)
print(a1%2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


### Converting Data Structure to Numpy array


In [6]:
import numpy as np

In [29]:
# converting list to numpy array
lst = [1,2,3,4,5]
array = np.array(lst)
print(array)
print(type(array))
print("*"*25)

lst_ = array.tolist()
print(lst_)
print(type(lst_))
print("*"*25)
# converting tuple to numpy array
tple = (1,2,3,4,5)
array = np.array(tple)
print(array)
print(type(array))
print("*"*25)



# converting set to numpy array
st = {1,2,3,4,5}
array = np.array(list(st))
print(array)
print(type(array))
print("*"*25)
print(str(array))
# converting string to numpy array
string = "Hello, World!"
array = np.array(list(string))
print(array)
print(type(array))
print("*"*25)

# converting dictionary to numpy array
dictionary = {"a":1, "b":2, "c":3}
array = np.array(dictionary)
print(array)
print(type(array))
print("*"*25)

print(np.array(dictionary.items()))


[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1, 2, 3, 4, 5]
<class 'list'>
*************************
[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1 2 3 4 5]
<class 'numpy.ndarray'>
*************************
[1 2 3 4 5]
['H' 'e' 'l' 'l' 'o' ',' ' ' 'W' 'o' 'r' 'l' 'd' '!']
<class 'numpy.ndarray'>
*************************
{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
*************************
dict_items([('a', 1), ('b', 2), ('c', 3)])


### Converting the Datatype to Numpy array

In [30]:
arr = np.array([1,2,3,3,4])
print(arr)

print(arr.astype("float"))

arr_ = arr.astype(np.float16)
print(arr_.dtype)
print(arr_.astype("str"))
print(arr_.astype("bool"))


[1 2 3 3 4]
[1. 2. 3. 3. 4.]
float16
['1.0' '2.0' '3.0' '3.0' '4.0']
[ True  True  True  True  True]


In [31]:
arr1 = np.array([1,2,3,4,5])
a = (str(arr1))
print(type(a))


# print(tuple(arr1))
print(list(arr1))
# del set
print(set(arr1))


<class 'str'>
[1, 2, 3, 4, 5]
{1, 2, 3, 4, 5}


### Copying elements in list and arrays

In [20]:
# copy system in the list
lst = [1,2,3,4,5]
lst1 = lst
# changing the value of lst
lst[0] = 100
print(lst)
# changes will be reflected in lst1
print(lst1)
print("-"*10)

# now changing the value of lst1
lst1[0] = 200
print(lst1)
print(id(lst1))
print(lst)
print(id(lst))                  # changes will reflected in both lists
print("-"*10)
print('*'* 25)
# copy system in the array
arr = np.array([1,2,3,4,5])
arr1 = arr
# changing the value of arr
arr[0] = 100
print(arr)
print(arr1)
print("-"*10)

# now changing the value of arr1
arr1[0] = 200
print(arr1)
print(id(arr1))
print(arr)
print(id(arr))
print("-"*10)                   # changes will be reflected in both arrays


[100, 2, 3, 4, 5]
[100, 2, 3, 4, 5]
----------
[200, 2, 3, 4, 5]
2020653440512
[200, 2, 3, 4, 5]
2020653440512
----------
*************************
[100   2   3   4   5]
[100   2   3   4   5]
----------
[200   2   3   4   5]
2020652953360
[200   2   3   4   5]
2020652953360
----------


In [32]:
# using copy function
lst = [1,2,3,4,5]
lst1 = lst.copy()       # will create a new copy of the list which is not linked to the original list
# changing the value of lst
lst[0] = 100
print(lst)
print(id(lst))
print(lst1)
print(id(lst1))
print("-"*10)

# changing the value of lst1
lst1[0] = 200
print(lst1)
print(lst)


print("*"*25)       
# copy system in the array
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()
# changing the value of arr
arr[0] = 100
print(arr)
print(arr1)
print("-"*10)

# changing the value of arr1
arr1[0] = 200
print(arr1)
print(arr)
print(id(arr1))
print(id(arr))
print("-"*10)




[100, 2, 3, 4, 5]
1996183644352
[1, 2, 3, 4, 5]
1996224864896
----------
[200, 2, 3, 4, 5]
[100, 2, 3, 4, 5]
*************************
[100   2   3   4   5]
[1 2 3 4 5]
----------
[200   2   3   4   5]
[100   2   3   4   5]
1996183400592
1996183400112
----------


In [33]:
# For simple lists: [:] works like a copy.
lst = [1,2,3,4,5]
lst1 = lst[:]
print(lst1)
lst[0] = 100
print(lst)
print(lst1)     # changes will not be reflected in both lists
print(id(lst))
print(id(lst1))
print("-"*10)
print('*'*25)
# arr1 = arr[:] doesn’t create a completely separate copy — it’s just a view of the same data.
arr = np.array([1,2,3,4,5])
arr1 = arr[:]
print(arr1)
arr[0] = 100
print(arr)
print(arr1)
print(id(arr))
print(id(arr1))
print("-"*10)





[1, 2, 3, 4, 5]
[100, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
1996224863808
1996224871808
----------
*************************
[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
1996224824016
1996183400112
----------


#### Adding, Sorting, remooving the elements 

In [34]:
import numpy as np
# Adding
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
con = np.concatenate((x,y))
print(con)
print("*"*25)

# sorting
z = np.array([2,3,64,8,6,95,2,67,9,1])
zs = np.sort(z)
print(zs)
print("*"*25)

#removing

[ 1  2  3  4  5  6  7  8  9 10]
*************************
[ 1  2  2  3  6  8  9 64 67 95]
*************************


#### Indexing and slicing the arrays

In [35]:
import numpy as np
# indexing
arr = np.array([1,2,3,4,5])
print(arr[0])       # positive indexng
print(arr[-1])      # negative indexing
print(arr[4])
print("_"*10)

# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[0][0])
print(arr[0][1])
print("*"*25)

# slicing
arr = np.array([1,2,3,4,5])
print(arr[0:2])
print(arr[:-2])         # negative slicing
print(arr[2:])
print(arr[:])


# 2D array  
arr = np.array([[1,2,3],[4,5,6]])
print(arr[:])
print(arr[0][:])
print(arr[1][:])


array = np.array([1,2,3,4,4,5,6,7,8,9])
print(array[0:len(array)+1])          # it will print 0 to 4 index


a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a>5])
print(a[a<5])
print(a[a>=5])
print("*"*25)
# divisible by two
print(a[a%2==0])
print("*"*25)
c = a[(a > 2) & (a < 11)]           # and condition(&)
print(c)
print("*"*25)
# using logical operator to create boolean value
five_up = (a > 5) | (a == 5)
print(five_up)
print("-"*25)
print(a[five_up])


1
5
5
__________
[1 2 3]
1
2
*************************
[1 2]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[1 2 3 4 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12]
[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
*************************
[ 2  4  6  8 10 12]
*************************
[ 3  4  5  6  7  8  9 10]
*************************
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
-------------------------
[ 5  6  7  8  9 10 11 12]


#### Generating random numbers arrays

In [36]:
print(np.random.rand())         # will create always random number between 0 and 1
print(np.random.rand(10))       # will create 10 random number between 0 and 1
print(np.random.rand(3,3))      # wll generate 3X3 random matrices between 0 and 1
print("*"*30)


print(np.random.randint(10))       # will create random number upto 10
print(np.random.randint(10,size= (5)))      # will create random  number with 1 row and 5 column
print(np.random.randint(1000, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))
print("*"*30)



# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))
print("*"*30)

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

0.8445002974525758
[0.4391938  0.8798212  0.46760324 0.22223152 0.87941551 0.13987163
 0.8367524  0.29212108 0.26004735 0.9853319 ]
[[0.97289837 0.25634956 0.5212242 ]
 [0.30367269 0.42192826 0.00169285]
 [0.08910126 0.00297578 0.44962259]]
******************************
0
[0 7 2 1 2]
[[ 28 394  85]
 [ 57 954 246]
 [647 289 787]]
[[136 193 148]
 [173 197 157]
 [142 128 150]]
******************************
[[0.77754916 0.11473814 0.91366061]
 [0.04250486 0.40694565 0.78788595]
 [0.10254686 0.07771493 0.04133556]]
******************************
[[3 5 0]
 [6 3 4]
 [5 5 5]]


#### Manging the randomness(seed)
- seed() is used to initialize the random number generator.
- Random number generators don’t generate truly random numbers — they generate pseudo-random numbers, and seed() bas unka starting point fix karta hai.

In [37]:
import numpy as np
print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))
# generating random numbers
print("*"*35)


# intializing seed function
import numpy as np
np.random.seed(2)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.40252768125933525
[0.44762044 0.40349586 0.95641608]
6
[[2 4 8 4 9]
 [3 3 5 8 2]
 [0 3 8 0 8]]
***********************************
0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [38]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(5)

# Run the loop 10 times
for i in range(10):
    # Generate an array of 1000 random integers (either 0 or 1)
    arr = np.random.randint(2, size=1000)
    
    # Count and print the number of ones and zeros in the array
    print(len(arr[arr == 1]), len(arr[arr == 0]))       #  array slicing kar raha hai → sirf un elements ko extract karega jo 1 hain
#    Is array ka length count karega → matlab kitne 1s hain

505 495
509 491
481 519
508 492
510 490
490 510
503 497
475 525
496 504
499 501


### Flatening and spliting the array

In [39]:
# two popular way to flatten the array .flatten(), ravel()
np.random.seed(1)
num = np.random.randint(1, 100, size=(3, 3))
print(num)

print("*"*25)
flat = num.flatten()         # it will convert the 2D array into 1D array
print(flat)
print("*"*25)

ravel = num.ravel()         # it will convert the 2D array into 1D array
print(ravel)


array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array)
print(array.ndim)       # it will return the dimension of the array# 3D array hai

print(array.flatten())       # it will convert the 3D array into 1D array

[[38 13 73]
 [10 76  6]
 [80 65 17]]
*************************
[38 13 73 10 76  6 80 65 17]
*************************
[38 13 73 10 76  6 80 65 17]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# spllitting the arrays:- matlab big NumPy array ko chhote-chhote tukdon mein todna 💥
# np.split
array = np.arange(20).reshape(4,5)
print(array)
print("*"*25)
print(np.split(array,2))
print("*"*25)
for i in np.split(array,2):
    print(i)


# np.vsplit:- vertical splitting
print(np.vsplit(array,2))    # it will split the array into 2 parts vertically
print("*"*25)
shape = (np.hsplit(array,5))
print(shape) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
*************************
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]
*************************
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]
*************************
[array([[ 0],
       [ 5],
       [10],
       [15]]), array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]])]


### Merging and stacking

In [42]:
# merging the arrays
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.concatenate((arr1,arr2,arr3, arr4))

print(concat_arr)       # merged into one and make 1d of all

stacked = np.stack((arr1,arr2,arr3,arr4),axis = 0)       # it will create 2D array with 4 rows and 1 column
print(stacked)         # it will create 2D array with 4 rows and 1 column


print("*"*25)
# hstack

import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.hstack((arr1,arr2,arr3,arr4))

print(concat_arr)

print("*"*25)

# vstack
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.vstack((arr1,arr2,arr3,arr4))

print(concat_arr)           # it will create 2D array with 4 rows and 1 column

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]
[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]
*************************
[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]
*************************
[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


In [4]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.stack((arr1,arr2,arr3,arr4), axis = 0)

concat_arr_ = np.stack((arr1,arr2,arr3,arr4), axis = 1)
print(concat_arr)       # creating transpose of of the arrays
print(concat_arr_)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]
[[1 1 9 8]
 [2 5 2 2]
 [3 2 3 9]
 [4 9 5 4]]


#### basic array operations :- addition , subtraction, multiplication , division

In [34]:
# adding the elements
data = np.array([1, 2])
ones = np.ones(2,dtype = int)
print(data + ones)
print("*"*25)
print(data- ones)
print("*"*25)
print(data*data)
print("*"*25)
print(data/data)


a = np.array([1, 2, 3, 4])
a.sum()
print("*"*25)
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis = 0))      # sum column wise implies sum over axis of rows
print("*"*25)
print(b.sum(axis = 1))      # sum row wise implies sum over axis of columns


# operation between a vector and a scalar or between arrays of two different sizes
data = np.array([1.0, 2.0])
data * 1.6

[2 3]
*************************
[0 1]
*************************
[1 4]
*************************
[1. 1.]
*************************
[3 3]
*************************
[2 4]


array([1.6, 3.2])

### unique items and counts

In [45]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)
print("*"*25)
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)
print("*"*25)
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
print("*"*25)
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)
print("*"*25)
unique_values = np.unique(a_2d, axis=0)  # unique rows
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]
*************************
[ 0  2  3  4  5  6  7 12 13 14]
*************************
[3 2 2 2 1 1 1 1 1 1]
*************************
[ 1  2  3  4  5  6  7  8  9 10 11 12]
*************************
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Transposing and reshaping matrix and flipping area

In [57]:
## Transpose of the array
arr = np.arange(6).reshape((2, 3))
print(arr)
print(arr.transpose())
print(arr.T)          # it will create transpose of the array

print("*"*25)
# reversing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.flip(arr))

# reversing 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)
print(np.flip(arr_2d, axis=1))  # reverse rows
print(np.flip(arr_2d, axis=0))  # reverse columns

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
*************************
[8 7 6 5 4 3 2 1]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### Linear Algebra 

#### dot produt

In [4]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
dot_product = np.dot(x, y)  # Dot product of x and y
print(dot_product)

# will throw an error because dimension mismatch, so it is must that dimension should be same
# xy = np.array([1,2,3])
# yz = np.array([4,5,6,7])
# dot_product = np.dot(xy, yz)  # Dot product of xy and yz

70


#### cross product

In [14]:
x = np.array([[1, 2], [3, 4]])
print(x)
y = np.array([[5, 6], [7, 8]])
print(y)

cross_product = np.matmul(x, y)  # Cross product of x and y
print(cross_product)


cross_product_ = np.matmul(y,x)  # Cross product of x and y
print(cross_product_)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [22]:
# determinant
x = np.array([[1, 2,1], [3, 4,5],[6,7,8]])
print(x)
print(x.shape)
print(x.ndim)       # it will return the dimension of the array# 3D array hai
print(x.size)       # it will return the size of the array
print(x.itemsize)   # it will return the item size of the array

det = np.linalg.det(x)  # Determinant of x
print(det)

[[1 2 1]
 [3 4 5]
 [6 7 8]]
(3, 3)
2
9
4
6.000000000000001


In [4]:
# transpose
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
# transpose of matrix
x_transpose = np.transpose(x)  # Transpose of x
print(x_transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [1]:
import numpy as np
# inverse of matrix:- possible only for square matrix and whose determinant != 0
matrix = np.array([[1, 2,3], [3, 4,5],[5,6,7]])
print(matrix)
inverse = np.linalg.inv(matrix) # Inverse of matrix
print(inverse)

print("*"*25)
# # will throw an error because the matrix is not square matrix
# x = np.array([[1, 2, 3], [4, 5, 6]])
# print(np.linalg.inv(x))

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]
 [-9.00719925e+15  1.80143985e+16 -9.00719925e+15]
 [ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]]
*************************


In [8]:
import numpy as np
# solving linear algebra
eq = np.array ([[1,2,3],[4,5,6],[7,8,10]])
print(eq)

sol = np.array([[10],[11],[12]])
print(sol)

solution = np.linalg.solve(eq,sol)
print(solution)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[[10]
 [11]
 [12]]
[[-9.33333333e+00]
 [ 9.66666667e+00]
 [ 3.55271368e-15]]


In [10]:
# eigen values and eigen vectors
import numpy as np
A = np.array([[5,4],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues,eigenvectors)

[6. 1.] [[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]


### Saving the numpy file

In [ ]:
# textfile
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
np.savetxt('data.txt',arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# numpy file 
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('data.npy',arr)

In [18]:
# csv file
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
np.savetxt("data1.csv", arr, delimiter = "," , header = "a,b,c")       # it will create csv file with comma separated values

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# json format
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
np.savetxt("data.json",arr,delimiter =  ",")       # it will create json file with comma separated values

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# yaml
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt("data.yaml",arr,delimiter =  ",")       # it will create yaml file with comma separated values

### Reading the files

In [34]:
# text file
data = np.loadtxt("data.txt")       # it will load the text file
print(data)
print(type(data))       # it will return the type of the data
print(data.shape)       # it will return the shape of the data
print("*"*25)
data1 = np.load("D:/PYTHON/ipynb/advance python/data.npy")
print(data1)       # it will load the numpy file

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>
(3, 3)
*************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Writing the data into the file

In [40]:
# replacing the exisiting the file
text = np.array([1,2,3,4])
np.savetxt("data.txt",text,delimiter = ",")       # it will create text file with comma separated values
np.loadtxt("data.txt")       # it will load the text file

array([1., 2., 3., 4.])

In [43]:
# appending the data to the exisiting file
import numpy as np
np.load("D:/PYTHON/ipynb/advance python/data.npy")

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])